# Generated by Django 6.0.6 on 2026-07-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_clicks', to='customers.customer')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['clicked_at'], name='reviews_rev_clicked_7707a0_idx'), models.Index(fields=['source'], name='reviews_rev_source_d83316_idx')],
            },
        ),
    ]
