# Generated by Django 6.0.6 on 2026-07-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('email_time', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_time', models.DateTimeField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='billing.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='notificatio_status_a242db_idx'), models.Index(fields=['email_sent'], name='notificatio_email_s_831cd9_idx'), models.Index(fields=['whatsapp_sent'], name='notificatio_whatsap_0669b8_idx'), models.Index(fields=['created_at'], name='notificatio_created_01830a_idx')],
            },
        ),
    ]
